# Generated by Django 3.2.25 on 2025-05-26 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='paument_status',
        ),
        migrations.AlterField(
            model_name='payments',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.orders'),
        ),
    ]
