# Generated by Django 3.2.25 on 2025-06-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250527_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='phone_no',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='payment_time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_vegan',
        ),
    ]
